spring.application.name=CarePulse
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Groq Integration
groq.api.key=${API_KEY}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}